
services:
  postgres:
    image: postgres:16.2
    env_file:
      - .env
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - '5050:80'

volumes:
  postgres_data: {}
